### ISSUE TITLE
Remote Connection

### ISSUE THREAD

**Issue by GameboyVlol** [GameboyVlol/Rat#4]
**Bug**
The future that needs to be added is remote connection to another computer
You can also contact me on discord to talk to me about this feature or anything else!

**Reason**
I opened this issue so the people that want to contribute know what to add :)

**How**
So this is how the new feature looks, when the target runs the jar file the info gets sent to a another jar file on the attacker’s computer and shows the info about the target. Even if the attacker’s computer is turned off the info still shows when he opens the app.
From the jar file on the computer you can control the target’s computer using buttons.

**contribute**
To contribute fork this repository commit your changes on a new branch on your fork and create a pull request!

**Comment by BeChris100** [comment]
Let me list things, what is wrong with this post:

## People will remain silent
They expect YOU to make the features, not making the people to make them tell you to give you ideas. You plan out and you make the features. This is the real concept of programming. Without planning on what to add into a project, it's like shooting yourself in the foot.

## Remote connection, Networking, Security and Device Management
Remote connection is basically calling on Networking. Do you have this kind of such a skill? If not, then don't even bother because you might be rewriting a lot of code. And I really mean, A LOT OF CODE. What you need to understand about networking is, how transport works, how you might want to decode / decrypt them and so on. I might suggest you to learn about device security and how Antiviruses work as well if you want to hide your "rat" from AVs.

By reading "Even if the attacker’s computer is turned off, the info still shows when he opens the app", you clearly mean that the computer is powered off and the info still shows. That is, what we call "caching" because the info is saved on the attacker's PC. You might as well need to learn on how System services work on different operating systems, since to this point, you only wrote for Windows-side target clients. What about the attacker jar and other operating systems such as Linux and macOS? Android does also support Java, so you might need to learn everything first, not make a repository and hope to god's heart that it works (unless god is not on your side if you tend to hack someone without their privileges or without their consent).

## Explaining some sentences you wrote
You wrote "So this is how the new feature looks, when the target runs the jar file the info gets sent to another jar file on the attacker’s computer" (LanguageTool, a web-based plugin, corrected your sentence, so don't attack me). This sentence here is total BS. Why? Read the networking chapter again.

## Conclusion
From looking at your GitHub's page, you are a beginner to programming, mostly due to many forks. You try to make your own version of a RAT (Remote Administration tool) without properly knowing, how networking works. If you do tend to tell me that you know about networking, I won't believe it. Showing me only about this "Webhook" that you wrote isn't enough because you used the library from a different repository. Sometimes, you need to start writing your own code and not always trust on other libraries, as some of them tend to have obfuscated code (especially Google libraries).

What I suggest you is to learn to code in Java fully, then share the code that you like to share on GitHub and other places, not without having proper knowledge. It's like Stack Overflow going toxic on you.
